apiVersion: v1
kind: Secret
metadata:
  name: tmi-cluster-env
  namespace: tmi-cluster
data:
  DB_HOST: bXlzcWwuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_USERNAME: cm9vdA==
#  DB_PASSWORD:
  DB_DATABASE: dG1pX2NsdXN0ZXJfdGVzdA==
#  REDIS_URL:
#  TMI_USERNAME:
#  TMI_PASSWORD:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tmi-cluster
  namespace: tmi-cluster
spec:
  selector:
    matchLabels:
      app: tmi-cluster
  template:
    metadata:
      labels:
        app: tmi-cluster
    spec:
      containers:
        - name: tmi-cluster
          image: derpierre65/tmi-cluster-test:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: tmi-cluster-env
                optional: false